# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: User Service CI

on:
  pull_request:
    branches: ['main']
  
jobs:
  user-service-job:
    runs-on: ubuntu-latest

    env:
      ENV: "TEST"
      SECRET_TOKEN: 1234567
      DB_TEST_URI: mongodb+srv://user3219:user3219@cluster0.fesq8vy.mongodb.net/?retryWrites=true&w=majority
      

    defaults:
      run:
        working-directory: ./user-service

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
